export const projects = [
    {
    id: "1",
    title:
      "Nexus Fintech Pipeline | Real-Time Transaction ETL | AWS · Airflow · Snowflake · Dbt · Python · Power BI",
    subtitle: "aws, dbt, airflow, python, snowflake, mysql, powerbi",
    description: `🏛️ Business Context
Nexus Fintech is a digital banking platform (fictional case study) that processes thousands of daily transactions across various payment methods. The project focuses on building a robust, automated infrastructure to move raw transaction data from an API simulation to a live executive dashboard.

⚠️ The Business Problem
The organization suffered from data silos and manual reporting delays. Transactional data generated by the banking core was stored in inconsistent JSON formats within a Data Lake (AWS S3), making it impossible for stakeholders to track daily sales, identify failed transactions, or detect anomalies in real-time. Without an automated pipeline, the business was "flying blind."

📈 Business Impact
By architecting and implementing this automated pipeline, I achieved the following:
Real-Time Visibility: Reduced data availability time from 24+ hours to near real-time, enabling immediate operational responses.

Operational Efficiency: Automated 100% of the ingestion process, eliminating manual S3-to-Snowflake imports and human error.

Pipeline Resilience: Implemented a "Chaos Mode" in the data generator to test the system against corrupted data, ensuring the dashboard remains a "single source of truth."

Scalability: Designed a modular system capable of handling thousands of new files daily through managed orchestration.

🛠️ Technical Stack

Orchestration: Astro CLI (Astronomer) – Managing containerized Apache Airflow environments for seamless pipeline scheduling.

Data Transformation: dbt (data build tool) – Implementing modular SQL modeling, data lineage, and testing to ensure high-quality, reliable datasets within the warehouse.

Data Warehouse: Snowflake – Optimized for cloud-native ingestion using External Stages and Lateral Flattening for semi-structured JSON parsing.

Infrastructure: Docker – Powering isolated environments for consistent development-to-production workflows.

Data Generation: Python (Boto3) – Custom-built generator for API simulation and real-time "Chaos Mode" injection.

Cloud Storage: AWS S3 – Acting as the scalable Data Lake for raw transaction landing zones.

Visualization: Power BI – Delivering executive-level insights via real-time dashboards.`,

    image: "/gif_nexus.gif",
    gallery: [
      "/projects-images/nexus-project/pipeline_nexus.png",
      "/projects-images/nexus-project/1dashboard.png",
      "/projects-images/nexus-project/2editor.png",
      "/projects-images/nexus-project/3aws.png",
      "/projects-images/nexus-project/4airflow.png",
      "/projects-images/nexus-project/5snowflake.png",
      "/projects-images/nexus-project/6python.png",
      "/projects-images/nexus-project/dbt.png",

        ],
    link: "",
  },
      {
    id: "1",
    title:
      "E-commerce Sales Optimization Dashboard | Snowflake Cloud (AWS) + Python + n8n Orchestration + Power BI Insights",
    subtitle: "aws, n8n, python, snowflake, mysql, powerbi",
    description: `“Apex Outdoors” (fictional case), managing daily sales across multiple regions.

Their reality: a team of four Data Entry specialists spending hours exporting, consolidating, and manually formatting Excel files from their online store just to produce a single sales report.

The result? Over $3,200 USD per month in operational costs, frequent human errors, and a 24-hour delay in business decision-making.

The Mission

Design and implement a fully automated, scalable, and cost-efficient data pipeline to eliminate manual reporting and provide near real-time business insights.

The Solution: Apex Sales Pipeline

I designed an event-driven data architecture that transformed a $3,200/month manual workflow into an automated cloud pipeline costing under $300/month.

1. Data Ingestion (Python)

A Python script simulates a real-time e-commerce API, continuously generating structured JSON data (orders, customers, timestamps).
Technologies: Python (json, datetime, random).

2. Workflow Orchestration (n8n)

n8n acts as the central orchestrator using scheduled triggers to execute the pipeline, validate data creation, and manage the data flow.
Technology: n8n.

3. Staging & Storage (AWS S3)

Raw JSON files are uploaded to an Amazon S3 bucket, creating a durable landing zone for raw data ingestion.
Technology: AWS S3.

4. Data Warehouse (Snowflake)

The pipeline loads data from S3 into Snowflake using COPY INTO, where SQL views parse JSON data, join geographic metadata (Lat/Lon), and structure it for analytics.
Technology: Snowflake.

5. Data Visualization (Power BI)

Power BI connects directly to the curated Snowflake views to deliver interactive dashboards including sales overview, heat maps, product insights, and system monitoring.
Technology: Power BI.

Business Impact

• 90% cost reduction ($3,200 → ~$300/month)
• Real-time decision making by eliminating 24-hour reporting delays
• Improved data accuracy by removing manual processing errors`,

    image: "/gif_apex_ecom.gif",
    gallery: [
      "/projects-images/apex_ecom/dashboard_1.png",
      "/projects-images/apex_ecom/product_2.png",
      "/projects-images/apex_ecom/map_3.png",
      "/projects-images/apex_ecom/settings_4.png",
      "/projects-images/apex_ecom/snowflake_5.png",
      "/projects-images/apex_ecom/aws_6.png",
      "/projects-images/apex_ecom/n8n_6.png",
      "/projects-images/apex_ecom/editor_7.png",
      "/projects-images/apex_ecom/pyton_8.png",
      "/projects-images/apex_ecom/gitbash_9.png",
      "/projects-images/apex_ecom/workflow_9.png",
        ],
    link: "",
  },

  
  {
    id: "2",
    title:
      "WFM Call center Intelligent Dashboard | Snowflake Cloud AWS + Power BI + Machine Learning Forecasting",
    subtitle: "aws, snowflake, mysql, powerbi",
    description: `I’m excited to share my latest Workforce Management (WFM) project. I transformed raw call center data into a high-level strategic decision tool by integrating a modern cloud tech stack.

                  What this Dashboard Tracks:
                  Trend Analysis: Real-time comparison of actual call volume against ML-driven forecasts to identify intraday patterns.

                  Daily Performance KPIs: High-level visibility of daily SLA (13.29%) and Total Calls to measure overall service health.

                  Efficiency Metrics: Constant tracking of Average Handle Time (493.98 sec) to monitor agent productivity and operational flow.

                  Leadership Insights: Detailed breakdown of performance by Team Leader and Agent, enabling data-driven coaching.

                  Staffing Alignment: Visual correlation between Scheduled Personnel and incoming demand to highlight coverage needs.

                  Core Features: Forecasting & Scheduling
                  ML-Powered Forecasting: Integrated Snowflake data to project expected volumes with confidence bands (Upper/Lower bounds) for anomaly prevention.

                  Scheduling Visualization: Implemented staffing lines to visually detect peak intervals where the operation is under-resourced.

                  Technical Stack Applied:

                  Cloud Data Warehouse: Data management and extraction utilizing Snowflake.
                  Advanced DAX: Developed measures for critical KPIs including SLA %, Avg AHT, and Actual vs. Predicted call counts.
                  Data Modeling: Performed data cleaning and transformation to align time granularity and manage complex relational schemas.`,

    image: "/Gift_Workforce_manangement_ Dashboard.gif",
    gallery: [
      "/projects-images/wfm-project/dashboard.png",
      "/projects-images/wfm-project/forecasting_snowflake.png",
      "/projects-images/wfm-project/modelling.png",
      "/projects-images/wfm-project/powerbi_editor.png",
      "/projects-images/wfm-project/aws.png"
    ],
    link: "",
  },
  {
    id: "3",
    title: "Operational Productivity & Overtime Impact Analysis Manufacturing Company | Power BI",
    subtitle: "powerbi",
    description: `Power BI Project | Operational Productivity & Overtime Impact Analysis
Manufacturing companies constantly face operational challenges like:

• Is overtime actually improving productivity — or just increasing costs?
• Which shift is truly the most efficient?
• Are we paying more per unit than we should?
• Which departments consistently meet performance targets?
• Are we experiencing diminishing returns during extended shifts?

To explore these questions, I built a Power BI dashboard simulating a real-world manufacturing environment serving U.S. automotive clients.
The analysis focused on:

✔ Target Achievement %
✔ Units per Hour (true productivity metric)
✔ Cost per Unit
✔ Overtime efficiency impact
✔ Department-level performance benchmarking

One key insight:

Overtime increased total output, but reduced efficiency per hour — suggesting diminishing productivity returns during extended shifts.
This project allowed me to apply DAX functions such as:

• CALCULATE (context manipulation)
• ALL & ALLEXCEPT (benchmarking)
• RANKX (department ranking)

More importantly, it reinforced something critical:

Operational analytics is not about charts — it's about helping leadership make better decisions.

Open to opportunities in Operational Analytics, Productivity Analysis, and Business Intelligence.
`,

    image: "/gift_operational.gif",
    gallery: [
      "/projects-images/operman_project/dashboard_clean.png",
      "/projects-images/operman_project/powerbi_editor.png",
      "/projects-images/operman_project/powerquery.png",
    ],
    link: "",
  },

];

// testimonio de mis estudios

export const testimonials = [

        {
   
    image: "./6sigma.png",
    name: "Six Sigma Yellow Belt",
    company: "6sigmastudy",
    link2:
      "https://drive.google.com/file/d/1dHTGjGK3ug0nETx0KjwXK9AK6XOaeHIZ/view",
  },
      {
   
    image: "./cssc.png",
    name: "Lean Six Sigma White Belt Certification",
    company: "The Council for Six Sigma Certification (CSSC)",
    link2:
      "https://drive.google.com/file/d/1IXTdpHEwazhJsvZ557oKa5hfOAG6QF19/view",
  },
    {
   
    image: "./udemy-2.png",
    name: "Microsoft Excel: From Beginner to Advanced(PowerPivots, Dashboards, Data cleaning, functions)",
    company: "Udemy",
    link2:
      "https://cert.efset.org/X4v8u9",
  },

  {
   
    image: "./ef-set.png",
    name: "EF SET English Certificate 50/100 (B1 Intermediate)",
    company: "EF SET",
    link2:
      "https://cert.efset.org/X4v8u9",
  },

  {
   
    image: "./certiprof.png",
    name: "Scrum Foundation",
    company: "CertiProf",
    link2: "https://drive.google.com/file/d/1JgShZ0h5NtPm_4Z96NYaGh0u0uf9i_m4/view",
  },

  {

    image: "./kodigo-logo.jpg",
    name: "Web developer (HTML, CSS, JavaScript, ReactJS, MySQL, APIs) ",
    company: "Academy Kodigo",
    link2:
      "https://drive.google.com/file/d/1K1bI9eWzp2h2XXI2tYOIo2TIdAc1Uy9u/view",
  },
    {

    image: "./uveg_logo.jpg",
    name: "Lic. en Ingenieria en sistemas (2023-Current[online])",
    company: "UVEG Universidad",
    link2: "#",
  },
];

export const skills = [
  "Excel",
  "Airflow",
  "Power BI",
  "MySQL",
  "Python",
  "Dbt",
  "Snowflake",
  "Git & GitHub",
];
